### ISSUE TITLE
你好，请教下action deploy的问题

### ISSUE THREAD

**Issue by felbry** [KaiOrange/yuannijueding#1]
我是在segmentfault下看到了你的评论
同时看了下你的action构建记录
和我目前碰到的问题一模一样
所以想请教下你是如何解决的

主要我觉得自己的服务器ssh配置都没什么问题
github存了私钥
服务器的authorized_keys也配了公钥
各种各样试都不行
麻烦有空回复一下吧，谢谢。

**Comment by KaiOrange** [comment]
这个我总结了一篇文章：[https://www.kai666666.top/2020/01/04/%E4%BD%BF%E7%94%A8GithubActions%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%BA%94%E7%94%A8%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88ECS%EF%BC%89/](https://www.kai666666.top/2020/01/04/%E4%BD%BF%E7%94%A8GithubActions%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%BA%94%E7%94%A8%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88ECS%EF%BC%89/)

希望对你能有所帮助。
如果还有什么问题可以继续在这里留言

**Comment by felbry** [comment]
> 这个我总结了一篇文章：https://www.kai666666.top/2020/01/04/%E4%BD%BF%E7%94%A8GithubActions%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%BA%94%E7%94%A8%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88ECS%EF%BC%89/
> 
> 希望对你能有所帮助。
> 如果还有什么问题可以继续在这里留言

我仔细看过了您的文章，感觉你把公钥和私钥配置好就能够成功构建了。
我这边比较奇葩的就是感觉都做的没问题，就是失败，这个失败的info也特别少，没法定位问题。

起初用的是我本地电脑上的 私钥，因为我本地已经连过服务器了，公钥也在服务器上。
结果不行，我在想是不是私钥有唯一标识，只能用在一台机器上。
于是我在服务器上又 ssh-keygen 了一对，新的私钥添加到github，公钥补充进了服务器的文件中。
结果还是不行。

目前猜测是服务器权限的问题，但是也没头绪。
而且我本地直接通过 rsync命令是可以轻松随意推到服务器上的，奇怪的很。

感谢回复，我继续摸索吧，如果成功了，我也会更新这个issue给别人参考。

**Comment by KaiOrange** [comment]
@felbry 
你服务器上的`authorized_keys`文件放的是你新生成的公钥吗？github中的`ACCESS_TOKEN`字段存的是相对应的私钥吗？

**Comment by felbry** [comment]
> authorized_keys

是的，红线上是本地机器的公钥，红线下是我在服务器新生成的公钥，一共两个
![image](https://user-images.githubusercontent.com/14942382/77297967-0e56ab80-6d25-11ea-89ec-7836335bb743.png)

**Comment by KaiOrange** [comment]
@felbry 
本地机器里面的公钥只要放在`id_rsa.pub`中就行了 `authorized_keys`中的公钥是用来连接服务器的 所以只要写新的就可以了 旧的没必要写 你把旧的公钥去掉 保证`authorized_keys`文件只有一个公钥试试

**Comment by felbry** [comment]
> @felbry
> 本地机器里面的公钥只要放在`id_rsa.pub`中就行了 `authorized_keys`中的公钥是用来连接服务器的 所以只要写新的就可以了 旧的没必要写 你把旧的公钥去掉 保证`authorized_keys`文件只有一个公钥试试

兄弟，我的内心是有点崩溃的，我踏马现在终于成功了
关于你的建议可能不太适用我，这样没什么问题，因为本身电脑比较多，每台电脑都有自己的key。

我的问题在于：我在github添加secret的时候没有多出**一个换行**
一开始我拷贝key时，是在命令行用cat命令，像这样
![image](https://user-images.githubusercontent.com/14942382/77305209-99896e80-6d30-11ea-9b1d-3c3443575178.png)
最后我被逼无奈通过open命令直接文本编辑器打开，ctrl+a全选再复制，粘贴进github时我发现末尾多了个换行，再试，就成功了。。。。

**Comment by KaiOrange** [comment]
@felbry 哈哈 太不容易了 恭喜恭喜
